### ISSUE TITLE
address_component not setting addressLine1 correctly.

### ISSUE THREAD

**Issue by Foonz** [Logicify/jquery-locationpicker-plugin#106]
Hi,

the Examples aswell as my test implementation doesn't seem to have access to the street information anymore.

The http response sets it correctly:

```
"address_components" : [
            {
               "long_name" : "29",
               "short_name" : "29",
               "types" : [ "street_number" ]
            },
            {
               "long_name" : "Lascygasse",
               "short_name" : "Lascygasse",
               "types" : [ "route" ]
            },
            {
               "long_name" : "Hernals",
               "short_name" : "Hernals",
               "types" : [ "political", "sublocality", "sublocality_level_1" ]
            },
            {
               "long_name" : "Wien",
               "short_name" : "Wien",
               "types" : [ "locality", "political" ]
            },
            {
               "long_name" : "Wien",
               "short_name" : "Wien",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "Österreich",
               "short_name" : "AT",
               "types" : [ "country", "political" ]
            },
            {
               "long_name" : "1170",
               "short_name" : "1170",
               "types" : [ "postal_code" ]
            }
         ]
```

bute the jquery-locationpicker-plugin "addressComponent" does not seem to access it correctly and therefore returns empty strings:

![image](https://cloud.githubusercontent.com/assets/5786370/20214614/93a1a04e-a80f-11e6-9a9b-a392248b9eca.png)

but in your code, you seem to set it at line 156:

`result.addressLine1 = [result.streetNumber, result.streetName].join(' ').trim();`

**Comment by Foonz** [comment]
the problem was, that there were no working examples or documentation of how to achieve this goal. if you provide the config option { addressFormat: 'street_address' } you get detailed information.

Hope this helps someone!

**Comment by ChaseGiunta** [comment]
Wow, this needs to better presented for those updating. The new addition `addressFormat` is a breaking change for those who relied on the street address.

**Comment by rvirani1** [comment]
+1
