### ISSUE TITLE
Initialize locationNameInput empty

### ISSUE THREAD

**Issue by ZombieHippie** [Logicify/jquery-locationpicker-plugin#11]
Is it possible to initialize the locationNameInput empty?

Otherwise would it be a good idea to clear the input value with `oninitialize`?

**Comment by dialogik** [comment]
You could your own JavaScript to clear the input field. I implemented a little jQuery snipplet that clears the field on focus:

    $( document ).ready(function() {
        $('input#address').focus(function() {
    	     $(this).val('');
        });
    });

**Comment by Sumragen** [comment]
You can set value of input element when 'locationpicker' component will be initialized.
```javascript             
$('#map').locationpicker({
   inputBinding: {
      locationNameInput: $('#input-address')
   },
   oninitialized : function (component) {
      $('#input-address').val('');
   }
});
```
