### ISSUE TITLE
Autocomplete bound not working

### ISSUE THREAD

**Issue by adarsh10** [Logicify/jquery-locationpicker-plugin#111]
I want to get suggestions restricted to a city (Bangalore, India). How to do that?

**Comment by Sumragen** [comment]
@adarsh10 Hi!
First of all, be sure that you use the last released version of [jquery-locationpicker-plugin](https://github.com/Logicify/jquery-locationpicker-plugin).
And the second one: [here](https://github.com/Logicify/jquery-locationpicker-plugin/issues/75#issuecomment-246288599) is my answer for the same question.

**Comment by Sumragen** [comment]
If you have a similar question - reopen that issue
