### ISSUE TITLE
Address, city, state, country, pin code in separate input boxes 

### ISSUE THREAD

**Issue by mmdgreat** [Logicify/jquery-locationpicker-plugin#15]
Hey,

Can you suggest how I can get address, city, state, country, pin code in separate input boxes using locationpicker plugin? Thanks!!

**Comment by ChaseGiunta** [comment]
I have this set up for my form- search from `street1` and it auto-fills in `street1`, `city`, `state`, `zip` . Though, if you select any other input, `street1` will go back to the full address. Any ideas how to fix this?

**Comment by samiulhaq** [comment]
Hello, 

What if I want to update the map when I update a zip code in the input field. any help will be really appreciated. 

Thanks
