### ISSUE TITLE
Allow passing options to the google map

### ISSUE THREAD

**Issue by manmartinez** [Logicify/jquery-locationpicker-plugin#16]
It would be great if you could pass options to the google map, as specified by Google Maps API V3. Maybe something like 

    var gmapDefaults = {
                zoom: settings.zoom,
                center: new google.maps.LatLng(settings.location.latitude, settings.location.longitude),
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                mapTypeControl: false,
                disableDoubleClickZoom: false,
                scrollwheel: settings.scrollwheel,
                streetViewControl: false,
                radius: settings.radius,
                locationName: settings.locationName,
                settings: settings,
                draggable: settings.draggable
    };

    var gmapContext = new GMapContext(this, $.extend({}, gMapDefaults, gMapOptions);

**Comment by dialogik** [comment]
Yeah, I support this. Especially the mouse handling like `disableDoubleClickZoom`, `scrollWheel` or `draggable` would be very handy...
