### ISSUE TITLE
Working with hidden DIVs

### ISSUE THREAD

**Issue by EnterateNorte** [Logicify/jquery-locationpicker-plugin#19]
This is not an issue, is more like a question

How can some one work with the map when its loaded to a hidden DIV then made apear via JQUERY?

**Comment by corvis** [comment]
Hey, here is an update: in version 0.1.12 I added new method which allows to update gmap widget.
Let's say you would like to use locationpicker in modal dialog:

```javascript
$('#us6-dialog').on('shown.bs.modal', function() {
    $('#us3').locationpicker('autosize');
});
```

Checkout examples folder for details.
