### ISSUE TITLE
Enter-key submits form when selecting a location

### ISSUE THREAD

**Issue by dexstar** [Logicify/jquery-locationpicker-plugin#2]
To prevent this put the following code at line 140:

```
            // Prevent form from being submitted if user hit enter.
            inputBinding.locationNameInput.keypress(function(event){
                if (event.keyCode === 13){ return false; }
            });
```

**Comment by joakimnl** [comment]
Has this been deliberately removed from source again? 

Could be nice with an option for it.

Cheers!

**Comment by franzliedke** [comment]
I'm assuming this was removed accidentally not even two months after this fix made it in, see this commit:
https://github.com/Logicify/jquery-locationpicker-plugin/commit/e356e689e8fb91e81efef8c0510439a2b629acc0

@corvis Could we have that fix back? :)

**Comment by hallaathrad** [comment]
@corvis If you please, could we at least be enlightened on why the fix was removed?

**Comment by hallaathrad** [comment]
Looks like the change doesn't work the intended way... Currently working on it, and will submit a PR asap.

**Comment by hallaathrad** [comment]
As promised, a PR to fix this behaviour. Please feel free to test and advise whether changes need to be made :)
