### ISSUE TITLE
Working with bootstrap modal

### ISSUE THREAD

**Issue by vaibhav3011** [Logicify/jquery-locationpicker-plugin#20]
Hi,
I want to show locationpicker in bootstrap modal. But I am unable to show map in modal.
Can you guide me how I can do that.

Thanks

**Comment by corvis** [comment]
Also since version 0.1.12 it is possible to use "autosize" method to fix map widget:

```javascript
$('#us6-dialog').on('shown.bs.modal', function() {
    $('#us3').locationpicker('autosize');
});
```

**Comment by adgfx** [comment]
Hi Corvis,
I am displaying my company location by default. Need a 'reset' button to fly back to the initial position at anytime. Is there an option? maybe $(#id).locationpicker('reset'); !!!
Thanks, 
AJ

**Comment by hydropik** [comment]
Hi all,
I need a reset button too, like you adgfx.
Does it possible to add this function to the next release?
Thanks,
LR

**Comment by 9px** [comment]
for solving the problem of autocomplete (auto-suggest) in bootstrap modal, only add this code to the last line of style:
```css
.pac-container{z-index:2000 !important;}
```

**Comment by incredibleX** [comment]
hey, i'm stuck at this http://stackoverflow.com/questions/31631777/logicify-location-picker-using-dynamic-change-for-input Please help

**Comment by Sumragen** [comment]
@incredibleX hi! Answer at your question is [here](https://github.com/Logicify/jquery-locationpicker-plugin/issues/57).
