### ISSUE TITLE
Problem with Umlaute (German)

### ISSUE THREAD

**Issue by dialogik** [Logicify/jquery-locationpicker-plugin#30]
The picker has problems with Umlaute (like `ü`) in the city name (and very likely in other fields, too). E.g. the city name `München` is truncated to `M`.

**Comment by cbhp** [comment]
No issue but wrong field, see json:
            {
               "long_name" : "München",
               "short_name" : "M",
               "types" : [ "locality", "political" ]
            },

short_name is the first 1-3 letters of the city.

**Comment by dialogik** [comment]
Uh I see. Sorry, my bad.
