### ISSUE TITLE
Autocomplete not working in modal

### ISSUE THREAD

**Issue by simamura87** [Logicify/jquery-locationpicker-plugin#32]
Actually everything is written in title.
Autocomplete is not working in modal window.

**Comment by corvis** [comment]
Hi most likely it is working but it is overlaped by modal dialog. Try to play with ```z-index``` of your dialog and\or element which wraps autocomplete popup (should be added to body).
See similar issue for reference: #20 looks like the same problem.

**Comment by simamura87** [comment]
Thanks. Indeed z-index works.
