### ISSUE TITLE
How i can see the satellite view ?

### ISSUE THREAD

**Issue by kashifnaseer** [Logicify/jquery-locationpicker-plugin#34]
Is there any option to see the satellite view ?

**Comment by cp0815** [comment]
i would also need the satellite view

**Comment by cp0815** [comment]
I just found it. 
you have to change the lines 250 or 251 in the js file:
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    mapTypeControl: false,


Change mapeTypeId for the style that is showen by default, f.e. change from ROADMAP to SATELLITE to show the satellite map by default.
Change mapTypeControl to true to show the buttons for Map and Satellite in the map.

**Comment by JamoCA** [comment]
In addition to using either `SATELLITE` or `HYBRID` mapTypeIds, you may want to use `tilt:0` so that Google Maps doesn't tilt the map view when zoomed in to a street level view.  (It'd be nice if these were options, but there are so many things you can do with the Google Maps API.)

**Comment by awgeorge** [comment]
You can access the map with `$('#us3').locationpicker('map').map;`

You will then be able to use googles built in functions. EG.

`$('#us3').locationpicker('map').map.setMapTypeId(google.maps.MapTypeId.SATELLITE);`
