### ISSUE TITLE
Any way to grab the map zoom level?

### ISSUE THREAD

**Issue by unitedworx** [Logicify/jquery-locationpicker-plugin#41]
hi all this is a superb plugin for easily grabbing lat and lon especially with the modal view.

I need to also grab the map zoom level. Any way I can do this? 

Thanks in advance

**Comment by xaviesteve** [comment]
:+1: I'd love this too!

**Comment by unitedworx** [comment]
Found out I can grab the zoom like this
var zoom = $('#geo-location-map').locationpicker('map').map.getZoom();

And set it as well when the map is loaded
 $('#geo-location-map').locationpicker('map').map.setZoom(14);
