### ISSUE TITLE
Geo lookup feature does not work when coordinates are changed.

### ISSUE THREAD

**Issue by iCHAIT** [Logicify/jquery-locationpicker-plugin#43]
Whenever I change the lat, long coordinates manually the marker shifts to a new position and rightly so , but the value of the location field remains unchanged as the coordinates are changed which is obviously wrong.

What is the solution?

**Comment by dufferzafar** [comment]
:+1:

**Comment by wadhwasahil** [comment]
hey , nice stuff coders.
