### ISSUE TITLE
Any other address component example to get correct street component?

### ISSUE THREAD

**Issue by azulkipli** [Logicify/jquery-locationpicker-plugin#45]
in my case i got this address when dragging marker to other coordinate

Jalan Jakarta No.21, Batununggal, Kota Bandung, Jawa Barat 40271, Indonesia

my code

```
$('#location_picker').locationpicker({
    location: {latitude: -6.8959712, longitude: 107.6309693},
    locationName: "",
    radius: null,
    zoom: 15,
    scrollwheel: true,
    inputBinding: {
        latitudeInput: $('#latitude'),
        longitudeInput: $('#longitude'),
        radiusInput: null,
        locationNameInput: $('#address')
    },
    enableAutocomplete: false,
    enableReverseGeocode: true,
});
```

if  i use this code as in example
```
function updateControls(addressComponents) {
    $('#address').val(addressComponents.addressLine1);
    $('#city').val(addressComponents.city);
    $('#province').val(addressComponents.stateOrProvince);
    $('#zipcode').val(addressComponents.postalCode);
    $('#country_id').val(addressComponents.country);
}

$('#location_picker').locationpicker({
    location: {latitude: -6.8959712, longitude: 107.6309693},
    radius: null,
    zoom: 15,
    enableAutocomplete: true,
    enableReverseGeocode: true,
    onchanged: function (currentLocation, radius, isMarkerDropped) {
        var addressComponents = $(this).locationpicker('map').location.addressComponents;
        updateControls(addressComponents);
    },
    oninitialized: function(component) {
        var addressComponents = $(component).locationpicker('map').location.addressComponents;
        updateControls(addressComponents);
    }
});
```

I got "21 Jl. Jakarta" for street component, 
In my country the correct format for street address is "Jalan Jakarta No.21"

how can i get correct street address format?

thank you

**Comment by cbhp** [comment]
Look at the json response, there is a field "formatted_address" with a fully prebuilt address.
```
"formatted_address" : "Jl. Jakarta No.21, Batununggal, Kota Bandung, Jawa Barat 40271, Indonesien",
```

**Comment by MarcMueltin** [comment]
Hmm, sorry, I did not get it yet. How exactly can I modify your code in order to get a let's say German street format? This is: first the street name, then the house number.

Thanks in advance for your help !

**Comment by cbhp** [comment]
@MarcMueltin Look at the formatted_address. This property contains the local formatted address.

**Comment by MarcMueltin** [comment]
Ah, all right, now I got it. I cannot access this formatted_address attribute from your example code, I would have to modify your javascript code. 

My suggestion: 
1. In setPosition replace
GmUtility.address_component_from_google_geocode(results[0].address_components);

with 

GmUtility.address_component_from_google_geocode(results[0].address_components, results[0].formatted_address);

2. In the line which starts with
address_component_from_google_geocode: function(address_components) {
add a 'formattedAddress' parameter (according to step 1)

3.  Further down the code lines do the following:
//result.addressLine1 = [result.streetNumber, result.streetName].join(' ').trim();  <- the old original code
addressParts = formatted_address.split(', ') // <- new code
result.addressLine1 = addressParts[0] // <- new code

So the addresLine1 is always in a local format. Am I missing sth. or would this be a feasible solution?

**Comment by azulkipli** [comment]
Yes thank you I was thinking the splitting solution for localized formatted
address but dont know how to do it yet, now you point me how to do it..I
think this is feasible solution, we can split other address part too from
this case.

Thank you

**Comment by Sumragen** [comment]
You can get context of map. For example in callback '**onchanged**':
```javascript
...
onchanged: function (currentLocation, radius, isMarkerDropped) {
   $(this).locationpicker('map');
}
...
```
Then simply get all street components from ['location']['addressComponents'].
For example:
```javascript
$(this).locationpicker('map').location.addressComponents;
```

**Comment by Sumragen** [comment]
@azulkipli hi! Also look at ticket #69. It's more useful to your issue.

**Comment by Jasiel1995** [comment]
function updateControls(addressComponents) {
        console.log(addressComponents)
       $('#google-street).val(addressComponents.addressLine1);
        $('#google-city).val(addressComponents.city);
        $('#google-state).val(addressComponents.stateOrProvince);
        $('#google-pc').val(addressComponents.postalCode);
        $('#google-country).val(addressComponents.country);
        $('#google-district).val(addressComponents.district);
        $("#google-numbre").val(addressComponents.streetNumber);
    }
