### ISSUE TITLE
How to add HTML5 Geolocation?

### ISSUE THREAD

**Issue by ollie007** [Logicify/jquery-locationpicker-plugin#49]
How to add HTML5 Geolocation?

How do i add the HTML5 Geolocation in order to initialise the start location to the user location?

**Comment by nevenne** [comment]
will you use some database to track

**Comment by ollie007** [comment]
there is the geolocation function in newer browsers

    navigator.geolocation.getCurrentPosition(function(position) {

not sure that fires quick enough for this script

**Comment by ollie007** [comment]
Someone correct this code for me thanks, not working

    $.fn.locationpicker.defaults = {
				var _myLat;
				var _myLong;
					navigator.geolocation.getCurrentPosition(function(position) {
						var _myLat = position.coords.latitude;
						var _myLong = position.coords.longitude;
					});

        location: {latitude: _myLat, longitude: _myLong},

**Comment by nevenne** [comment]
https://cordova.apache.org/docs/en/2.5.0/cordova_geolocation_geolocation.md.html

**Comment by ollie007** [comment]
SO why wont it pass the location the defaults?

**Comment by nevenne** [comment]
add my skype call me

**Comment by ollie007** [comment]
i dont skype LOL   check the script

**Comment by ollie007** [comment]
maybe i need some quote characters?

**Comment by nevenne** [comment]
i need more informations

**Comment by nevenne** [comment]
did you add plugin

**Comment by ollie007** [comment]
i am hacking the script to add in the geolocation codes

**Comment by nevenne** [comment]
do you have whatsup

**Comment by ollie007** [comment]
how do you add plugins to this script??

    locationpicker.jquery.js

**Comment by nevenne** [comment]
ok  tell me  do you making cordova or what thats why i insiste skype call i
dont have enough informations

**Comment by nevenne** [comment]
https://plugins.jquery.com/locationpicker/

**Comment by ollie007** [comment]
LOOk there is enough info, you gave me the site to get the geolocation so add it to 

    locationpicker.jquery.js

**Comment by Sumragen** [comment]
@ollie007 hi! It's to simple. If you want get user location just write that
```javascript
if(navigator.geolocation){
    navigator.geolocation.getCurrentPosition(function (position) {
       //do something
    })
}
```
