### ISSUE TITLE
Start collapsed with Bootstrap BUT no map?

### ISSUE THREAD

**Issue by ollie007** [Logicify/jquery-locationpicker-plugin#50]
Start collapsed with Bootstrap BUT no map? i start the initialisation collapsed with bootstrap BUT the map wont show?

**Comment by nevenne** [comment]
send me files

**Comment by nevenne** [comment]
my skype is nevenne

**Comment by devkiran** [comment]
I have a similar issues with bootstrap, the map view is not visible.
![map issues](https://cloud.githubusercontent.com/assets/4593041/10751111/1dcb583a-7ca3-11e5-988c-f42b96faece5.png)

Any idea about this issues ?

**Comment by colerua** [comment]
I'm having this issue using bootstrap, if I remove the css file for bootstrap it works correctly.  Any ideas why?

**Comment by colerua** [comment]
Actually, I got the map working but the search for location isn't working at this point

**Comment by Sumragen** [comment]
@devkiran try to call '**_resize_**' event of google maps. It must help to you.
```javascript
...
oninitialized : function () {
   var map = $('#us-map').locationpicker('map').map;
   google.maps.event.trigger(map, 'resize');
}
...
```

**Comment by Sumragen** [comment]
Actually, call this method. It is the same, like a my previous answer.
```javascript
$('#mapId').locationpicker('autosize'); 
```
