### ISSUE TITLE
Modal: Location Name Issue

### ISSUE THREAD

**Issue by aryalprakash** [Logicify/jquery-locationpicker-plugin#51]
Change by Location Name is not working on Bootstrap Modal even when autocomplete is enabled: true.

**Comment by othyn** [comment]
It's an issue with the css z-index property of the location select dropdown, noticed it when I first saw the demo on the examples website.

Add "z-index: 5001;", or anything above 1050 (as that is the z-index of BS modals), to the class "pac-container". That is the class that the hidden search dropdown element uses, you can view it if you open up your inspector, scroll to the bottom to see the generated elements.

Hope that helps.
