### ISSUE TITLE
locaionpicker In wordpress admin

### ISSUE THREAD

**Issue by ghost** [Logicify/jquery-locationpicker-plugin#53]
I added locaionpicker to a plugin in wordpress but i get this error 

inputBinding.radiusInput.value is not a function

http://i.imgur.com/FliKEV3.png

**Comment by nevenne** [comment]
check jqery 160 line

**Comment by nexxoz** [comment]
i did, what should i do ?

  if (inputBinding.radiusInput) {
            inputBinding.radiusInput.val(gmapContext.radius).change();
        }

**Comment by Sumragen** [comment]
@ghost I think it was happened because you select incorrect jQuery selector of 'radiusInput'.
Use something like this:
```html
<input type="text" class="form-control" id="us3-radius" />
<div id="us3" style="width: 550px; height: 400px;"></div>
<script>
   $('#us3').locationpicker({
      inputBinding: {
         radiusInput: $('#us3-radius'),
      }
   });
</script>
```

**Comment by Sumragen** [comment]
If it doesn't help you, please, reopen this issue.
