### ISSUE TITLE
Need marker to be fixed, only map should be movable

### ISSUE THREAD

**Issue by Sundarasan** [Logicify/jquery-locationpicker-plugin#56]
I do not want marker to be draggable, it should be **fixed** to the center of `div`, I want only the map to be draggable.

So that **user can just drag the map and set the location by its fixed marker**.

**Note:** Now the user has to search the marker, if lost while playing around the map. A fixed marker will help a lot.

**Comment by churiart** [comment]
Any idea on this request?

**Comment by adisos** [comment]
I also need this.

**Comment by Sumragen** [comment]
Now it's too simple, just set property '**_markerDraggable_**' to **false**.
For example:
```javascript
$('#map-example').locationpicker({
   draggable: true,
   markerDraggable: false //default - true
});
```

**Comment by adisos** [comment]
Wow, thank you! @Sumragen

**Comment by adisos** [comment]
@Sumragen 
Your PR not solving problem by the way.

**Comment by Sumragen** [comment]
@adisos because it for the time being not merged with master branch

**Comment by adisos** [comment]
No, I picked JS file from your develop branch. The thing is you fixed marker, it cannot be moved, but when you drag map it still moves, instead of staying in center of div.

**Comment by Sumragen** [comment]
@adisos sorry, i wasn't understood issue at the beginning. 
Here is updated example
```javascript
$('#map-example').locationpicker({
   draggable: true,
   markerInCenter: true
});
```
I hope, now [it's](https://github.com/Logicify/jquery-locationpicker-plugin/commit/6c99fb4a0b0b59e3e7f248bd0eaa3fb2e02000d0) solve your issue.

**Comment by adisos** [comment]
Yeah, it's working now, but it is so choppy

**Comment by mykhie** [comment]
Hi @Sumragen ,i have tried markerDraggable but it is not working

**Comment by Sumragen** [comment]
Hi @mykhie. My commits in **_development_** branch, and still not merged with _master_. You can checkout [this](https://github.com/Logicify/jquery-locationpicker-plugin/tree/development) branch.

**Comment by amyth** [comment]
I think it still does not work. The marker appears in the center once the I have dragged and dropped the map. Shouldn't the marker stay in center even while I am moving the map ?
