### ISSUE TITLE
City property from addressComponents empty

### ISSUE THREAD

**Issue by JPuigV** [Logicify/jquery-locationpicker-plugin#62]
The issue "How can I get proper city name? #24" happens again.

If you pick this location: "144-15 68th Rd, Flushing, NY 11367, EE. UU.". The addressComponents does not have the "city" property. It happens in other places of NY also.

Thanks

**Comment by Sumragen** [comment]
@JPuigV hi! Look at the same ticket #69. It must help you.

**Comment by Sumragen** [comment]
If it doesn't help you, please, reopen this issue
