### ISSUE TITLE
Change coordinates on the map with change event on the coordinates inputs

### ISSUE THREAD

**Issue by Al3xR0** [Logicify/jquery-locationpicker-plugin#64]
How can I reinitialize the map by using new coordinates that are added automatically? 

I am using the map in a modal but the coordinates are out of the modal. 

I am updating the coordinates automatically, and I tried to trigger change event on them but the coordinates from map don`t update like this, I have to manually add something to the field in order to update. I don`t know why the change event doesn't work on the coordinates input.

**Comment by Sumragen** [comment]
Hi @Al3xR0. Look at this ticket #57. Your issue is the same.
