### ISSUE TITLE
How do you hide the marker?

### ISSUE THREAD

**Issue by testerdev** [Logicify/jquery-locationpicker-plugin#65]
How do you hide the marker?

**Comment by Sumragen** [comment]
I think it will be more simply. [	386b6db](https://github.com/Logicify/jquery-locationpicker-plugin/commit/386b6dbf80e66f0110297457a1361c6cc8ffe9b5)   
If you need to hide marker - just set property '**_markerVisible_**' to **false**, and if need to hide selected area - set property '**_radius_**' to **0**.
You can programmatically set '**_visible_**' property like this:
```javascript
$('#mapExample').locationpicker('map').marker.setVisible(true); //false - to hide
```
