### ISSUE TITLE
Autocomplete cannot select city/suburb (i.e. broad area)

### ISSUE THREAD

**Issue by bwenstar** [Logicify/jquery-locationpicker-plugin#69]
Hello,

As the title states, I have implemented functionality similar to the 'Subscribing for Events' example seen on this page (http://logicify.github.io/jquery-locationpicker-plugin/#usage).

When I select a city as a location, for example 'Sydney, New South Wales, Australia' it autocompletes to '343 George St, Sydney NSW 2000, Australia'.

However the example that Google supplies allows you to select a city as a location rather than a specific address. (https://developers.google.com/maps/documentation/javascript/examples/places-searchbox).

Is there something I'm missing to fix this issue?  

```
	$(document).ready(function() {
		$('#map').locationpicker({
			location: {latitude: -27.4732212, longitude: 153.02787250000006},	
			radius: 1,
			inputBinding: {
		        latitudeInput: $('#us2-lat'),
		        longitudeInput: $('#us2-lon'),

		        locationNameInput: $('#us2-address')
    		},
    		    enableAutocomplete: true,
                onchanged: function (currentLocation, radius, isMarkerDropped) {
                    // Uncomment line below to show alert on each Location Changed event
                    //alert("Location changed. New location (" + currentLocation.latitude + ", " + currentLocation.longitude + ")");
                }
		});
	});
```

Any help would be greatly appreciated.

**Comment by Sumragen** [comment]
Now you can set _addressFormat_" one of the [types](https://developers.google.com/maps/documentation/geocoding/intro?hl=en#Types). 
By the way default value is "_postal_code_". It means if you pick "_addressFormat_" to "_localy_" and location haven't "_localy_" data "_locationNameInput_" will be consist of data from "_postal_code_".
