### ISSUE TITLE
Maps show up only on the upper left corner when shown after hidden

### ISSUE THREAD

**Issue by yfscoin** [Logicify/jquery-locationpicker-plugin#7]
First, thanks a lot for the great plugin, this was my 'EXACT' requirement and coudnt believe someone had a plugin to do just that. Being a non-programmer by profession, this was a life saver!
1. My page has a structure something like this:

<pre><code>&lt;div class=&quot;geo&quot;&gt;<br />
&lt;div id=&quot;maps&quot; style=&quot;width: 100%; height: 400px;&quot;&gt;&lt;/div&gt;<br />
&lt;/div&gt;</code></pre>

1. On document ready I have a function that hides the parent div
   
     <pre><code>$(document).on("pagecreate","#CommSchedulingPage",function(){
     $(".geo").hide();</code></pre>
2. I have button, when click on it, I show the parent div
   
   <pre><code>$(".geo").show();</code></pre>
3. On show , the maps only occupy the upper left portion of the #maps div as shown in attached image.

I initialize location picker as below at the end body section:, should I add anything else? Need help.

```
$(function(){
$('#maps').locationpicker({
location: {latitude: 13.204492, longitude: 77.707691},    
radius: 500,
inputBinding: {
    latitudeInput: $('#lat'+'1'),
    longitudeInput: $('#long'+'1'),
    radiusInput: $('#radius'+'1'),
    locationNameInput: $('#address'+'1')
},
enableAutocomplete: true,
onchanged: function(currentLocation, radius, isMarkerDropped) {
//alert("Location changed. New location (" + currentLocation.latitude + ", " + currentLocation.longitude + ")");
$('#lat'+'1').val(currentLocation.latitude);
$('#long'+'1').val(currentLocation.longitude);
$('#radius'+'1').val(radius);


}
});
});
```
# 

Actual page in action: http://www.yfs.co.in/webui/CommScheduling.html

Click yes for 'Notify users at certain locations only?'
and then click yes for 'Want to add additional locations to notify?'
# 

![mapsproblem](https://cloud.githubusercontent.com/assets/7189260/3063220/e2e20262-e236-11e3-8f6f-550ec4585899.PNG)

**Comment by SvetlinStaev** [comment]
@ZombieHippie - did you make it work with the `ul.dropdown-menu`. I am trying to do it in this way but the map seems to be off-center.

**Comment by ZombieHippie** [comment]
Haha, I don't remember at all, nor do I have the codebase where I used it
available to me anymore :-/ sorry.

**Comment by cmarfil** [comment]
Perfect with visibility:hidden! thanks!
