### ISSUE TITLE
unable to bind two input fields with map

### ISSUE THREAD

**Issue by waqasraza123** [Logicify/jquery-locationpicker-plugin#74]
here is my code
`$("#end_location").click(function(){
        $("#map_modal").openModal();
        $('#place_map_on_popup').locationpicker({
            location: {latitude: 33.7182, longitude: 73.0605 },
            locationName: "",
            radius: 100,
            zoom: 15,
            scrollwheel: true,
            inputBinding: {
                latitudeInput: null,
                longitudeInput: null,
                radiusInput: null,
                locationNameInput: $("#ending_location_input")
            },
            enableAutocomplete: true,
            enableReverseGeocode: true
        });
    });

    $("#start_location").click(function(){
        $("#map_modal").openModal();
        $('#place_map_on_popup').locationpicker({
            location: {latitude: 33.7182, longitude: 73.0605 },
            locationName: "",
            radius: 100,
            zoom: 15,
            scrollwheel: true,
            inputBinding: {
                latitudeInput: null,
                longitudeInput: null,
                radiusInput: null,
                locationNameInput: $("#starting_location_input")
            },
            enableAutocomplete: true,
            enableReverseGeocode: true
        });
    });
    $("#close_modal").click(function(){
        $("#map_modal").closeModal();
    });`

only one of the fields is binded whichever I select first from frontend.

**Comment by Sumragen** [comment]
Hi @waqasraza123! For example you can write something like that
```html
<div id="us3" style="width: 550px; height: 400px;"></div>
<div class="m-t-small">
    <label class="p-r-small col-sm-1 control-label">Lat.:</label>

    <div class="col-sm-3">
        <input type="text" class="form-control" style="width: 110px" id="us3-lat"/>
    </div>
    <label class="p-r-small col-sm-2 control-label">Long.:</label>

    <div class="col-sm-3">
        <input type="text" class="form-control" style="width: 110px" id="us3-lon-first"/>
    </div>
    <div class="col-sm-3">
        <input type="text" class="form-control" style="width: 110px" id="us3-lon-second"/>
    </div>
</div>
<script>
    $('#us3').locationpicker({
        inputBinding: {
            latitudeInput: $('#us3-lat'),
            longitudeInput: $('#us3-lon-first')
        }
    });
    $('#us3-lon-second').on('change', function (e) {
        var valueOfSecondField = $('#us3-lon-second').val();
        $('#us3-lon-first').val(valueOfSecondField).trigger(e)
    });
    $('#us3-lon-first').on('change', function (e) {
        var valueOfFirstField = $('#us3-lon-first').val();
        $('#us3-lon-second').val(valueOfFirstField);
    });
</script>
```
