### ISSUE TITLE
componentRestrictions

### ISSUE THREAD

**Issue by ajarti** [Logicify/jquery-locationpicker-plugin#75]
Hi all,
Any way to easily add componentRestrictions to the geocode? 

I need to restrict the lookup country.

Any help appreciated.

**Comment by Sumragen** [comment]
@ajarti hi! Now it simply, just write your preferences like that
```javascript
$('#mapId').locationpicker({
   location: {
      latitude: 46.15242437752303,
      longitude: 2.7470703125
   },
   inputBinding: {
      locationNameInput: $('#nameInputId')
   },
   enableAutocomplete: true,
   autocompleteOptions: {
      types: ['(cities)'],
      componentRestrictions: {country: 'fr'}
   }
});
``` 
P.S. need to wait when my commit will be merged with master branch

**Comment by ajarti** [comment]
@Sumragen sorry for the late reply, many thanks for the feedback, much appreciated!
