### ISSUE TITLE
embeding this in a component in angular 2

### ISSUE THREAD

**Issue by aTylerRice** [Logicify/jquery-locationpicker-plugin#81]
I am trying to embed this in a component template in angular 2 but the div just comes up blank and doesn't work. Anyone get this working in angular?

**Comment by aTylerRice** [comment]
I ended up appending the script tag to the component and that worked!
```
var s = document.createElement("script");
  s.type = "text/javascript";
  s.src = "/assets/js/locationpicker.jquery.js";
  this.elementRef.nativeElement.appendChild(s);
```

**Comment by ranouf** [comment]
Hi,

How did you succeed to bind the longitude and latitude and address?

Cedric
