### ISSUE TITLE
Autocomplete not working on address input

### ISSUE THREAD

**Issue by colerua** [Logicify/jquery-locationpicker-plugin#86]
I have it all working except when I type in the address input nothing happens.

I'm using it in a bootstrap modal
`						Location:
						<input type="text" id="us2-address" style="width: 200px"/>
						Radius: <input type="text" id="us2-radius" value='300'/>
						<div id="us2" style="width: auto; height: 400px;"></div>
						Lat.: <input type="text" id="us2-lat" value="<?php echo $currentLat; ?>"/>
						Long.: <input type="text" id="us2-lng" value="<?php echo $currentLng; ?>"/>
`

`
<script src="_scripts/locationpicker.jquery.js"></script>
	$('#select-location-modal').on('shown.bs.modal', function (e) {
		var currLat = $('#us2-lat').val();
		var currLng = $('#us2-lng').val();
		var currRadius = $('#us2-radius').val();
		$('#us2').locationpicker({
			location: {latitude: currLat, longitude: currLng},
			radius: currRadius,
			inputBinding: {
		        latitudeInput: $('#us2-lat'),
		        longitudeInput: $('#us2-lng'),
		        radiusInput: $('#us2-radius'),
		        locationNameInput: $('#us2-address')
		    },
				enableAutocomplete: true
		});
	});
`

I'm not sure what is wrong with it.  Have included the needed elements:

`	<script type="text/javascript" src='http://maps.google.com/maps/api/js?key=KEYHERE&sensor=false&libraries=places'></script>
`

and I also have this running on the same page if you think it might have an affect:
`	$geoLoc = unserialize(file_get_contents('http://www.geoplugin.net/php.gp?ip='.$_SERVER['REMOTE_ADDR']));
`

**Comment by Sumragen** [comment]
@colerua hmm.. It's strangely. I have tried re-create your project with that issue, but without 'geoplugin', and it works absolutely fine.
 Are you sure that key was created [like that](https://github.com/Logicify/jquery-locationpicker-plugin/issues/85#issuecomment-246318493)? (maybe port was forgotten, when you set HTTP referrers at step 4, for example _http://localhost**:9000**_)

**Comment by Sumragen** [comment]
@colerua also, try this
```javascript
$('#select-location-modal').on('shown.bs.modal', function (e) {
   $('#us2').locationpicker('autosize');
}
```

**Comment by Sumragen** [comment]
@colerua and one more :) 
look at this ticket #32
I hope, it must help you.
