### ISSUE TITLE
Map type have no effect

### ISSUE THREAD

**Issue by PanBagnat** [Logicify/jquery-locationpicker-plugin#92]
Hello.

I would like to apply the terrain type to the map but it have no effect. Do you know why?

```
        $('#event_place').locationpicker({
            location: {latitude: {{=latitude_value}}, longitude: {{=longitude_value}}},
            radius: 0,
            locationName: "{{=T('Start location')}}",
            inputBinding: {
                latitudeInput: $('#latitude'),
                longitudeInput: $('#longitude'),
                locationNameInput: $('#event_address')
            },
            mapTypeId: google.maps.MapTypeId.TERRAIN,
            enableAutocomplete: true
            });
```

Thanks, regards.

**Comment by Sumragen** [comment]
Hi @PanBagnat! 
Do you have any errors in console? Because i tried to re-create your issue and when removed properties 'location' & 'locationName' it's work fine.

**Comment by PanBagnat** [comment]
Hi Sumragen.
No sorry, there's not any error in console, with Chrome or Firefox.

Here is my JS processed.

```
        $('#event_place').locationpicker({
            location: {latitude: 44.9392226256, longitude: 6.82276877217},
            radius: 0,
            locationName: "Luogo partenza",
            inputBinding: {
                latitudeInput: $('#latitude'),
                longitudeInput: $('#longitude'),
                locationNameInput: $('#event_address')
            },
            mapTypeId: google.maps.MapTypeId.TERRAIN,
            enableAutocomplete: true
            });
```
I've also tried like you to take off the properties 'location' & 'locationName', without success.

Perhaps there's something wrong with the way that I call the Google maps API?
In the head:
    <script type="text/javascript" src='https://maps.google.com/maps/api/js?key=MYKEY&sensor=false&libraries=places'></script>
    <script src="{{=URL('static','js/locationpicker/locationpicker.jquery.js')}}"></script>

Thanks, regards.

**Comment by Sumragen** [comment]
@PanBagnat, you have forgotten to describe how you call Google maps API.
Are you override **mapTypeId** or element **#event_place** after map initialized?

**Comment by PanBagnat** [comment]
@Sumragen
Sorry, so in the head:
    <script type="text/javascript" src='https://maps.google.com/maps/api/js?key=MYKEY&sensor=false&libraries=places'></script>
    <script src="{{=URL('static','js/locationpicker/locationpicker.jquery.js')}}"></script>

>Are you override mapTypeId or element #event_place after map initialized?
No. JS is only the one I've posted before.

**Comment by Sumragen** [comment]
@PanBagnat 
Actually, ability to change 'mapTypeId' have added with release [0.1.14](https://github.com/Logicify/jquery-locationpicker-plugin/releases/tag/0.1.14). 
So, my question :) Are you sure that you use [last version](https://github.com/Logicify/jquery-locationpicker-plugin/releases/tag/0.1.15) of our plugin?

**Comment by PanBagnat** [comment]
I was using 0.1.13. Thanks for the support and the plugin.
