### ISSUE TITLE
Problems with google.maps.event.addDomListener

### ISSUE THREAD

**Issue by samhk222** [Logicify/jquery-locationpicker-plugin#93]
Hi guys, first of all, great plugin.

I'm having a issue with the google.maps.event.addDomListener. I have to redraw every marker when the maps changes (not only the draggable marker). The proper way of doing that is with 

google.maps.event.addListener(map, 'idle', function(){
 var bounds = map.getBounds();
 lat = bounds.getNorthEast().lat();
 lng = bounds.getSouthWest().lng();
} );

but after calling the locationpicker it´s impossible to bind anything to the google map object. It's possible to create a workaround for this ? I tried in every way that i could find, but was wortless =(

**Comment by Sumragen** [comment]
Hi @samhk222! Thanks. :)
So, first of all i want recommend to you use a 'subscribe' method of jquery-locationpicker, for example:
```javascript
$('myMapId').locationpicker('subscribe', {
   event: 'idle',
   callback: function(){
      var bounds = map.getBounds();
      lat = bounds.getNorthEast().lat();
      lng = bounds.getSouthWest().lng();
   }
});
```

And next one, are you sure that 'map' object is map from locationpiker?
```javascript
$('myMapId').locationpicker('map').map;
```

[More methods from locationpicker](http://logicify.github.io/jquery-locationpicker-plugin/#plugin-options)

**Comment by samhk222** [comment]
@Sumragen tankyou very, very much for your response. 

Unfortunately i had to create my own solution (from scratch), because the "subscribe" method wasn't clear  (at least for me) in the documentation =( and it's so simple to use, after seeing this example. My bad
