### ISSUE TITLE
Set marker position by click instead of drag

### ISSUE THREAD

**Issue by arogachev** [Logicify/jquery-locationpicker-plugin#94]
It's not something crucial, but I think it will be better if we can set marker position by click. Drag is OK, but in this case in order to select new position, current position should also stay in view. In some situations this is uncomfortable and we need either to continuously move marker and scroll map or filter by exact location.

I think it will be better to replace drag with click, but it can also be available through option.

**Comment by arogachev** [comment]
I saw 0.1.14 version released, there is new option appeared called `markerDraggable`, I tried to set it to `false` and thought that way I will be able to use click instead of drag. But in this case I can't use neither click nor drag to change marker positions, it's completely frozen, posiiton can only be changed using autocomplete search. So the problem is still actual.

**Comment by Sumragen** [comment]
Hi @arogachev!
I have already given an answer to a similar issue. Look [here](https://github.com/Logicify/jquery-locationpicker-plugin/pull/60#issuecomment-248910861).

**Comment by arogachev** [comment]
@Sumragen Sorry, didn't notice it because issue was closed. It will be great to have this code snippet as part of documentation in this case.

**Comment by Sumragen** [comment]
@arogachev I will add it to [examples](http://logicify.github.io/jquery-locationpicker-plugin/#examples).

**Comment by arogachev** [comment]
@Sumragen Thanks. This method works fine. But after click even marker is set to selected position, hand cursor moves to the side. It's kind of not expected behavior (I expect it to stay where marker's new position is). Any tips on that?

Also any chance to wrap this code into more simple option like `selectByClick` or something like that?

**Comment by Sumragen** [comment]
@arogachev why is it not expected behavior? You don't do any changes with cursor position, just picked pin location.
